- hosts: sandbox
  become: yes
  become_user: root
  tasks:
    - name: Install http server
      yum:
        name: httpd

    - name: start http server
      service:
        name: httpd
        state: started
        enabled: yes
