- hosts: ec2-sandbox
  become: yes
  become_user: root
  vars:
    - ansible_distribution_major_version: 7
  pre_tasks:
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"
  
    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-community-server']
        mysql_log_error: ""
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
  tasks:
  roles:
    - hostname
    - unix_groups
    - unix_users
    - httpd
    - pymysql
    - {role: sudoers/allow-all, group_name: group_a}
    - {role: sudoers/allow-httpd, group_name: group_b}
    - cron/yum_autoupdate
    - role: geerlingguy.mysql
      mysql_root_password: hogehoge
      mysql_databases:
        - name: l4a_db
          encoding: utf8
          collation: utf8_unicode_ci
        - name: guestbook
          encoding: utf8
          collation: utf8_unicode_ci
      mysql_users:
        - name: l4a_user
          host: "%"
          password: fugafuga
          priv: "l4a_db.*:ALL"
        - name: guestbook
          host: "%"
          password: guestbookpass
          priv: "guestbook.*:ALL"
    - php
    - git
    - role: php-guestbook
      db_host: localhost
      db_name: guestbook
      db_user: guestbook
      db_pass: guestbookpass
      tags: deploy
